FROM python:3.9.5-slim

RUN pip install pipenv

WORKDIR /app

ENV MYSQL_HOST db
ENV MYSQL_USER root
ENV MYSQL_DB bookmark
ENV MYSQL_PORT 3306

COPY Pipfile* .

RUN pipenv lock --keep-outdated --requirements > requirements.txt
RUN pip install -r requirements.txt

ADD . .

RUN pip install .

CMD [ "waitress-serve", "--call", "--port=5555", "app:create_app"]